/**
 * Generates a CSS file header comment with package name and timestamp.
 *
 * @param packageName - Defaults to `"valcss"`
 * @returns A CSS block comment string.
 *
 * @example
 * getHeaderComment() // "/* \nGenerated by valcss \nLast updated: 2024-01-01 12:00 \n*​/\n"
 */
export function getHeaderComment(packageName = "valcss"): string {
    const now = new Date();
    const timestamp = now.toISOString().split("T")[0] + " " + now.toTimeString().slice(0, 5);

    return `/* \nGenerated by ${packageName} \nLast updated: ${timestamp} \n*/\n`;
}
